CREATE DATABASE procMak;

CREATE TABLE Companys(
    CompanyID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NameCompany VARCHAR(255) NOT NULL,
    EmailCompany VARCHAR(255) NOT NULL UNIQUE,
    CreateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Suscriptions(
    SuscriptionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CompanyID INT NOT NULL,
    SuscriptionType ENUM('FREE','PREMIUM','EXPERT') DEFAULT 'FREE',
    SuscriptionStatus ENUM('ACTIVE','CANCELLED') DEFAULT NULL,
    CreateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EndDate DATE
);

CREATE TABLE UsersCompany(
    UserCompanyID INT (11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CompanyID INT,
    EmailCompany VARCHAR(255) NOT NUL,
    NameUser VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CONSTRAINT UsersCompany FOREIGN KEY (CompanyID) REFERENCES Companys(CompanyID),
    CreateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Clients(
    ClientID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CompanyID INT(11),
    CustomerName VARCHAR(255) NOT NULL,
    RFC VARCHAR(255) NOT NULL UNIQUE,
    Adress  VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone INT(11) UNIQUE,
    CONSTRAINT ClientCompany FOREIGN KEY (CompanyID) REFERENCES Companys(CompanyID),
    DateRegistration TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE Orders(
    OrderID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CompanyID INT,
    ClientID INT,
    UserID INT,
    OrderDetailID INT,
    DateRegistration TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE OrdersDetails(
    OrderDetailID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OrderID INT 
)